source 'https://rubygems.org'

gem 'github_api'
gem 'launchy'
gem 'terminal-table'
gem 'bitbucket_rest_api', github: 'codeship/bitbucket'
gem 'git', github: 'larsxschneider/ruby-git', branch: 'git-mirror'
gem 'pry'
